# Generated by Django 4.0.2 on 2022-03-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=20)),
                ('specialist', models.CharField(max_length=40)),
            ],
        ),
    ]
