# Generated by Django 4.0.2 on 2022-03-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SavePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('weight', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('services', models.CharField(max_length=40)),
                ('serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.services')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tablets', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.savepatient')),
            ],
        ),
    ]
